In [5]:
import numpy as np
# a=(1,2,3,4)
# print(type(a))
p=np.array((1,2,3,4))
print(p)
print(type(p))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
p=np.arange(10)
print(p)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
p=np.arange(2,100,2)
print(p)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [8]:
p=np.arange(1,100,2)
print(p)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
p=np.zeros(3)  #to get zeros
print(p)

[0. 0. 0.]


In [ ]:
p=np.ones(3)     #to get ones
print(p)

[1. 1. 1.]


In [12]:
p=np.zeros((3,3),int)
print(p)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#to create matrix
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(p)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#to get identity matrix
p=np.eye(3)
print(p)
#or
p=np.identity(3)
print(p)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
