In [3]:
import numpy as np
a=np.arange(1,8)
print(a)

[1 2 3 4 5 6 7]


In [10]:
#to slice array
print(a[1:5])
print(a[1:])
print(a[:5])
print(a[-4:-1])
print(a[3])

[2 3 4 5]
[2 3 4 5 6 7]
[1 2 3 4 5]
[4 5 6]
4


In [11]:
#to copy array to another variable
b=a
print(b)

[1 2 3 4 5 6 7]


In [ ]:
#to change an array element of both array
a[2]=10
print(a)
print(b)

[ 1  2 10  4  5  6  7]
[ 1  2 10  4  5  6  7]


In [13]:
#to change an array element of original array
a[2]=11
c=a.copy()
print(c)

[ 1  2 11  4  5  6  7]
