In [ ]:
import numpy as np
a=np.array((1,2,3,4,5))
b=np.array((6,7,8,9,10))
c=np.concatenate((a,b))    #to concatenate 2 array
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
#to concatenate 2 matrix
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8],[6,5],[3,2]])
c=np.concatenate((a,b),axis=1)
print(c)

d=np.array([[1,2,3],[4,5,6],[7,8,9]])
e=np.array([[9,8,7],[6,5,4],[3,2,1]])
f=np.concatenate((d,e))
print(f)


[[1 2 3 9 8]
 [4 5 6 6 5]
 [7 8 9 3 2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
a=np.array([1,6,3,6,5,6])
print(a)
x=np.where(a==6)   #to serach an element and get its index
print(x)

[1 2 3 4 5 6]
(array([5], dtype=int64),)


In [17]:
a=np.array([1,2,3,2,4])
x=np.where(a==2)
print (x[0])

[1 3]
