In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.transpose(a)) #to get transpose
 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.trace(a)) #to get sum of diagonal elements

15


In [9]:
a=np.array([[1,3,2],[6,4,2],[4,2,7]])
b=np.array([[7,2,4],[1,6,2],[8,3,6]])
print(np.dot(a,b)) #to get product of 2 matrices

[[26 26 22]
 [62 42 44]
 [86 41 62]]


In [ ]:
a=np.array([[1,4,3],[4,2,7],[3,8,2]])
print(np.linalg.inv(a)) #to get the inverse of a matrix

[[-0.66666667  0.20512821  0.28205128]
 [ 0.16666667 -0.08974359  0.06410256]
 [ 0.33333333  0.05128205 -0.17948718]]


In [ ]:
a=np.array([[1,4,3],[4,2,7],[3,8,2]])
print(np.linalg.matrix_rank(a)) #to get the rank of a matrix


3


In [13]:
a=np.array([[1,4,3],[4,2,7],[3,8,2]])
print(np.linalg.eig(a))
print(np.linalg.eigvals(a))

EigResult(eigenvalues=array([11.76707427, -1.18816519, -5.57890908]), eigenvectors=array([[-0.41717085, -0.88667107,  0.10894851],
       [-0.63607747,  0.15954142, -0.70487593],
       [-0.64913322,  0.4340057 ,  0.70091379]]))
[11.76707427 -1.18816519 -5.57890908]
