To perform dot product of 2 matrices


In [4]:
import numpy as np


In [7]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1, 3],[2, 8],[6, 4]])
print("Dot product of matrices:")
print(np.dot(a, b))


Dot product of matrices:
[[23 31]
 [50 76]]


To perform transpose of a matrix

In [8]:
a=np.array([[1,3,5],[2,5,8],[9,4,1]])
print("Transpose of the matrix :")
print(np.transpose(a))

Transpose of the matrix :
[[1 2 9]
 [3 5 4]
 [5 8 1]]


To get sum of diagonal elements of a matrix

In [9]:
a=np.array([[4,2,6],[3,2,6],[1,3,8]])
print("Sum of diagonal elements of the matrix:")
print(np.trace(a))

Sum of diagonal elements of the matrix:
14


To find the rank of a matrix

In [11]:
a=np.array([[1,3,5],[3,2,6],[3,8,5]])
print("Rank of the matrix:")
print(np.linalg.matrix_rank(a))

Rank of the matrix:
3


To find the determinant of a matrix

In [12]:
a=np.array([[1,3,5],[2,6,3],[8,4,7]])
print("Determinant of the matrix:")
print(np.linalg.det(a))

Determinant of the matrix:
-139.99999999999994


To find the Inverse of a matrix

In [13]:
a=np.array([[2,4,3],[6,5,2],[1,8,3]])
print("Inverse of the matrix:")
print(np.linalg.inv(a))

Inverse of the matrix:
[[-0.01587302  0.19047619 -0.11111111]
 [-0.25396825  0.04761905  0.22222222]
 [ 0.68253968 -0.19047619 -0.22222222]]


To find the eigen values and eigen vectors

In [14]:
a=np.array([[2,5,4],[6,2,4],[8,5,2]])
print("Eigen vectors :")
print(np.linalg.eig(a))
print("Eigen values:")
print(np.linalg.eigvals(a))


Eigen vectors :
EigResult(eigenvalues=array([12.43259165, -3.82520759, -2.60738406]), eigenvectors=array([[-0.51537437, -0.63697969, -0.14943614],
       [-0.54876956,  0.13492267, -0.53005273],
       [-0.65821063,  0.75898139,  0.83469333]]))
Eigen values:
[12.43259165 -3.82520759 -2.60738406]
