convert fahrenheit degree to centigrade degree.

In [3]:
import numpy as np
fahrenheit=np.array((72,43,114,89,65))
celsius=(fahrenheit-32)*5/9
print("Fahrenheit Values = ",fahrenheit)
print("Celsius values = ",celsius)

Fahrenheit Values =  [ 72  43 114  89  65]
Celsius values =  [22.22222222  6.11111111 45.55555556 31.66666667 18.33333333]


create a random array with 1000 elements and  compute the average variance, standard deviation.

In [4]:
arr=np.random.rand(1000)
average=np.mean(arr)
variance=np.var(arr)
standard_deviation=np.std(arr)
print("Average is : ",average)
print("Variance is : ",variance)
print("Standard Deviation is : ",standard_deviation)

Average is :  0.5041729191246808
Variance is :  0.0831249103579807
Standard Deviation is :  0.28831390940775076


convert angles from degrees to randians.

In [5]:
degree=np.array((23,67,90,29,50))
radian=np.deg2rad(degree)
print("Degree : ",degree)
print("Radian : ",radian)


Degree :  [23 67 90 29 50]
Radian :  [0.40142573 1.1693706  1.57079633 0.50614548 0.87266463]


Calculate difference between neighbouring elements .

In [7]:
numbers=np.array((2,17,89,45,63))
difference=np.diff(numbers)
print("New array is : ",difference)

New array is :  [ 15  72 -44  18]


To sort a given complex array using the real part and imaginary part.

In [12]:

array = np.array([2+1j, 4+2j, 3+6j, 8+2j, 5+4j])
indices = np.lexsort((array.imag, array.real))
sorted_array = array[indices]
print("Sorted array is:", sorted_array)


Sorted array is: [2.+1.j 3.+6.j 4.+2.j 5.+4.j 8.+2.j]


To create 1D Array with random numbers and print values greater than 4.

In [31]:
array1=np.random.randint(1,10,10) #low,high,size
print(array1)
for x in array1:
    if x>4:
        print(x)

[2 1 2 1 9 8 9 4 2 4]
9
8
9


Create a 1D array with random numbers and search a particular number given by user.

In [32]:
array2=np.random.randint(1,9,10)
print(array2)
num=int(input("Enter the number to search :"))
if num in array2:
    print(num ,"found in array")
else:
    print(num,"not found in array")

[5 4 1 1 8 3 2 1 1 7]
5 found in array


To save a given array to text file and load it.

In [23]:
array3=np.array((34,67,23,56,43))
print("Original array :",array3)
np.savetxt("array4.txt",array3)
load=np.loadtxt("array4.txt")
print("Loaded",load)

Original array : [34 67 23 56 43]
Loaded [34. 67. 23. 56. 43.]


To create an array of all even integers from 30 to 60.

In [24]:
array4=np.arange(30,61,2)
print("Even numbers between 30 and 60:",array4)

Even numbers between 30 and 60: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


To compute sum of all elements,sum of each column and sum of each row of a given array.

In [29]:
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Matrix :",p)
sum=np.sum(p)
print("Sum is :",sum)
col=np.sum(p,axis=0)
print("Sum of column :",col)
row=np.sum(p,axis=1)
print("Sum of row:",row)


Original Matrix : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum is : 45
Sum of column : [12 15 18]
Sum of row: [ 6 15 24]
